FROM alpine:3.15

RUN apk add --no-cache bash postgresql-client

COPY scripts/create-tables.sh /usr/local/bin/init-db.sh

COPY internal/sql/schema /internal/sql/schema

RUN chmod +x /usr/local/bin/init-db.sh

ENTRYPOINT ["/bin/sh", "/usr/local/bin/init-db.sh"]
