version: "3"

services:
  postgres:
    image: registry.docker.ir/postgres:16.2-alpine3.19
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  ideyar:
    image: ghcr.io/mosaic-2/ideyar-server/ideyar:production
    depends_on:
      - postgres
    ports:
      - "8888:8888"
      - "8080:8080"
    environment:
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_HOST=postgres
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - DB_LOG=$DB_LOG
      - SECRET_KEY=$SECRET_KEY
      - MAIL_PASS=$MAIL_PASS
    volumes:
      - ideyar_data:/home/app/images
    restart: always
volumes:
  postgres_data:
  ideyar_data:
