CREATE TABLE IF NOT EXISTS post (
	id BIGINT GENERATED ALWAYS AS IDENTITY,
	title VARCHAR(255) NOT NULL,
	user_id BIGINT NOT NULL,
	minimum_fund DECIMAL(28, 6) NOT NULL,
	fund_raised DECIMAL(28, 6) NOT NULL DEFAULT 0
)