// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: api/liveness.proto

/*
Package LivenessService is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package LivenessService

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/emptypb"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_Liveness_CheckLiveness_0(ctx context.Context, marshaler runtime.Marshaler, client LivenessClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq emptypb.Empty
	var metadata runtime.ServerMetadata

	msg, err := client.CheckLiveness(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_Liveness_CheckLiveness_0(ctx context.Context, marshaler runtime.Marshaler, server LivenessServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq emptypb.Empty
	var metadata runtime.ServerMetadata

	msg, err := server.CheckLiveness(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterLivenessHandlerServer registers the http handlers for service Liveness to "mux".
// UnaryRPC     :call LivenessServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterLivenessHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterLivenessHandlerServer(ctx context.Context, mux *runtime.ServeMux, server LivenessServer) error {

	mux.Handle("GET", pattern_Liveness_CheckLiveness_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/IdeYarAPI.Liveness/CheckLiveness", runtime.WithHTTPPathPattern("/liveness/checkliveness"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_Liveness_CheckLiveness_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_Liveness_CheckLiveness_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterLivenessHandlerFromEndpoint is same as RegisterLivenessHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterLivenessHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterLivenessHandler(ctx, mux, conn)
}

// RegisterLivenessHandler registers the http handlers for service Liveness to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterLivenessHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterLivenessHandlerClient(ctx, mux, NewLivenessClient(conn))
}

// RegisterLivenessHandlerClient registers the http handlers for service Liveness
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "LivenessClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "LivenessClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "LivenessClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterLivenessHandlerClient(ctx context.Context, mux *runtime.ServeMux, client LivenessClient) error {

	mux.Handle("GET", pattern_Liveness_CheckLiveness_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/IdeYarAPI.Liveness/CheckLiveness", runtime.WithHTTPPathPattern("/liveness/checkliveness"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_Liveness_CheckLiveness_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_Liveness_CheckLiveness_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_Liveness_CheckLiveness_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"liveness", "checkliveness"}, ""))
)

var (
	forward_Liveness_CheckLiveness_0 = runtime.ForwardResponseMessage
)
