# .github/workflows/ci.yml

name: Go CI/CD with Docker Compose

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  # Use a token or password stored in GitHub secrets

      - name: Build Docker images
        run: docker-compose build

      - name: Spin up services for tests
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: docker-compose up -d

#  test:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v2
#
#      - name: Run tests
#        run: docker-compose exec ideyar go test ./...
#
#      - name: Tear down services
#        if: always()
#        run: docker-compose down

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy
        env:
          # Set necessary environment variables for your deployment strategy
          DEPLOY_ENV: production
        run: |
          echo "Deploying to production..."
          # Add your deployment commands here
          # Example: ssh user@server 'bash -s' < deploy_script.sh